name: md-docs GitHub deploy

description: Deploy generated website to GitHub pages.

author: Arjan Geertsema

inputs:

  destination_directory:
    description: Directory where to deploy the generated website. Defaults to empty which is the root.
    required: false

runs:

  using: composite

  steps:
    
    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ github.token }}
        publish_dir: dist
        destination_dir: ${{ inputs.destination_directory }}
