name: publish test results

description: Github action to publish test execution files to Azure and trigger GitHub living documentation workflow.

author: Arjan Geertsema

inputs:
  
  github_token:
    description: Github [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) with Github living documentation repositories **public_repo** or **repo** scope.
    required: true

  credentials:
    description: Azure credentials.
    required: true

  storage_account:
    description: Name of the Azure storage account where the test execution container is located.
    required: true

  storage_container:
    description: Name of the Azure storage container where test execution files are located.
    required: true

  pattern:
    description: A glob pattern to match living documentation yaml files.
    required: false
    default: ./**/living-documentation.yml

runs:
  using: 'node12'
  main: 'dist/index.js'
