name: test

on:
  workflow_dispatch: 
  push:
  pull_request:  
    types: [opened]

jobs:
  
  test:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        uses: ./build
        with:
          working_directory: ./test-files/build

      - name: Github Deploy
        uses: ./github/deploy
        with:
          destination_directory: products
          working_directory: ./test-files/build

      - name: Azure Deploy
        uses: ./azure/deploy
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          storage_account: synionstorage
          storage_container: tests
          storage_bucket: test-deploy
          cdn_resource-group: synion
          cdn_profile: synion-cdn
          cdn_endpoint: docs-synion-www
          working_directory: ./test-files/build

      - name: Publish test results
        if: always()
        uses: ./azure/publish
        with:
          github_token: ${{ github.token }}
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          storage_account: synionstorage
          storage_container: tests
          pattern: ./test-files/publish/**/living-documentation.yml

      - name: Download test results
        uses: ./azure/download
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          storage_account: synionstorage
          storage_container: tests
          github_token: ${{ github.token }}
          repository: ${{ github.repository }}