name: test

on:
  
  pull_request:
  
    types: [opened]

jobs:
  
  test:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      
      - run: cd test-files/build      
      - uses: ./build