name: test

on:
  workflow_dispatch: 
  push:
  pull_request:  
    types: [opened]

jobs:
  
  test:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      
      - uses: ./build
        with:
          working_directory: ./test-files/build

      - name: Deploy
        uses: ./github/deploy
        with:
          destination_directory: products
          working_directory: ./test-files/build