name: test

on:
  workflow_dispatch: 
  push:
  pull_request:  
    types: [opened]

jobs:
  
  test:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      
      - run: cd test-files/build      
      - uses: ./build
        with:
          working_directory: ./test-files/build